### ISSUE TITLE
CSS property not exported from react-print

### ISSUE THREAD

**Issue by career-tokens** [OnedocLabs/react-print-pdf#1]
I wanted to add a google font to my template . Hence I tried to follow the docs :
![image](https://github.com/OnedocLabs/react-print-pdf/assets/134730030/47807e70-797b-42a2-a003-384575471f56)

But on running , I get the error "'CSS' is not exported from '@onedoc/react-print' (imported as 'CSS')."
![image](https://github.com/OnedocLabs/react-print-pdf/assets/134730030/7c659a48-72f7-4af1-aff6-50438883393a)

Another way as mentioned in the docs: using the import url in a css file and then using it is not working either.

It would be great if this issue could be fixed.

**Comment by Titou325** [comment]
Hey @career-tokens, thanks for reporting this!

This may be because your client SDK is not up to date, as the export has only been recently added (see https://github.com/OnedocLabs/react-print-pdf/blob/main/src/index.ts#L22)

You should be able to get rid of that error using `npm i -s @onedoc/react-print@latest`

Let me know if this works!

**Comment by career-tokens** [comment]
Okay sure I will try that and let you know.
